# SAYN sample project. Follow the tutorial for more details:
# https://173tech.github.io/sayn/tutorials/tutorial_part1

required_credentials:
  # List of credential names used by tasks in the project
  - warehouse

# Credential used by sql and autosql tasks
default_db: warehouse

parameters:
  base_url:  '' #no prefix for prod
  api_key: ''
  teams:
    - 15
    - 39
    - 1883502
    - 7390454
    - 5
    - 8214850
    - 8255756
    - 2586976
    - 7119388
    - 726228
    - 1838315
    - 6209166
    - 111474
    - 8254400
    - 7391077
    - 8260983
    - 8204512
    - 350190

